version: '2'

services:
  mysql:
    image: mysql:5.7.21
    volumes:
      - ~/workspace/docker-volumes/mysql-fe-conta:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-conta
  conta:
    image: fernandoe/fe-conta-server
    links:
      - mysql:mysql
    ports:
      - "9000:8000"
    environment:
       DATABASE_URL: mysql://root:password@mysql:3306/fe-conta
  criptomoeda:
    build: .
    volumes:
      - ./src:/app
    links:
      - mysql:mysql
      - conta:conta
    ports:
      - "9001:8000"
    environment:
       DATABASE_URL: mysql://root:password@mysql:3306/fe-criptomoeda
