# Generated by Django 2.0.2 on 2018-03-02 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('criptomoedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criptomoedas.Moeda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
